export const AppearanceTable = [
  {
    DieRoll: "01-13",
    HairColor: "Brunette",
    HairStyle: "Short Wavy Hair",
    EyeColor: "Light Blue",
    Complexion: "Dusky Olive",
  },
  {
    DieRoll: "14-26",
    HairColor: "Blonde",
    HairStyle: "Long Hair with Straight Bangs",
    EyeColor: "Dark Green",
    Complexion: "Bronze",
  },
  {
    DieRoll: "27-34",
    HairColor: "Auburn",
    HairStyle: "Short Hair with Ponytail",
    EyeColor: "Hazel",
    Complexion: "Milky White",
  },
  {
    DieRoll: "35-42",
    HairColor: "Sable",
    HairStyle: "Braided Hair",
    EyeColor: "Brown",
    Complexion: "Ebony",
  },
  {
    DieRoll: "43-50",
    HairColor: "Crimson",
    HairStyle: "Bob Cut",
    EyeColor: "Crimson",
    Complexion: "Light Red",
  },
  {
    DieRoll: "51-58",
    HairColor: "Silver",
    HairStyle: "Twintails",
    EyeColor: "Silver",
    Complexion: "Yellow",
  },
  {
    DieRoll: "59-67",
    HairColor: "White",
    HairStyle: "Pixie Cut",
    EyeColor: "Light Green",
    Complexion: "Brown",
  },
  {
    DieRoll: "68-75",
    HairColor: "Sky Blue",
    HairStyle: "Wolf Cut",
    EyeColor: "Dark Blue",
    Complexion: "Golden",
  },
  {
    DieRoll: "76-83",
    HairColor: "Light Green",
    HairStyle: "Parted Bangs",
    EyeColor: "Pink",
    Complexion: "Dark Brown",
  },
  {
    DieRoll: "84-91",
    HairColor: "Lilac",
    HairStyle: "Mohawk",
    EyeColor: "Purple",
    Complexion: "Light Salmon",
  },
  {
    DieRoll: "92-99",
    HairColor: "Iridescent",
    HairStyle: "Choose",
    EyeColor: "Choose",
    Complexion: "Choose",
  },
  {
    DieRoll: "00",
    HairColor: "NA",
    HairStyle: "Bald",
    EyeColor: "Each Eye Different",
    Complexion: "Choose",
  },
];
