export const RaceTable = [
  {
    Race: "Dwarf",
    BaseHeight: 41,
    HeightMod: "+ 1d10",
    BaseWeight: 105,
    WeightMod: "+ 4d10",
    BaseAge: 35,
    AgeMod: "+ 4d6",
    PriceMod: 2,
  },
  {
    Race: "Elf",
    BaseHeight: 58,
    HeightMod: "+ 2d6",
    BaseWeight: 70,
    WeightMod: "+ 3d10",
    BaseAge: 100,
    AgeMod: "+ 5d6",
    PriceMod: 5,
  },
  {
    Race: "Gnome",
    BaseHeight: 36,
    HeightMod: "+ 1d6",
    BaseWeigth: 68,
    WeightMod: "+ 5d4",
    BaseAge: 60,
    AgeMod: "+ 3d12",
    PriceMod: 3,
  },
  {
    Race: "Half-Elf",
    BaseHeight: 53,
    HeightMod: "+ 3d4",
    BaseWeight: 85,
    WeightMod: "+ 3d12",
    BaseAge: 16,
    AgeMod: "+ 2d6",
    PriceMod: 2.5,
  },
  {
    Race: "Half-Orc",
    BaseHeight: 55,
    HeightMod: "+ 1d6",
    BaseWeight: 100,
    WeightMod: "+ 3d12",
    BaseAge: 16,
    AgeMod: "+ 2d6",
    PriceMod: 0.75,
  },
  {
    Race: "HalfLing",
    BaseHeight: 30,
    HeightMod: "+ 2d8",
    BaseWeight: 48,
    WeightMod: "+ 5d4",
    BaseAge: 20,
    AgeMod: "+ 3d4",
    PriceMod: 4.0,
  },
  {
    Race: "Human",
    BaseHeight: 55,
    HeightMod: "+ 2d10",
    BaseWeight: 90,
    WeightMod: "+ 6d10",
    BaseAge: 16,
    AgeMod: "+ 2d6",
    PriceMod: 1.0,
  },
];
